import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a1a1a",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#2a2a2a",
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    padding: 8,
    marginRight: 8,
  },
  backButtonText: {
    color: "#1f87fc",
    fontSize: 24,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
  },
  markAllButton: {
    padding: 8,
  },
  markAllText: {
    color: "#1f87fc",
    fontSize: 14,
    fontWeight: "500",
  },
  filterContainer: {
    flexDirection: "row",
    backgroundColor: "#2a2a2a",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  filterTab: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 16,
    borderRadius: 20,
    backgroundColor: "#3a3a3a",
  },
  activeFilterTab: {
    backgroundColor: "#1f87fc",
  },
  filterText: {
    color: "#8e8e93",
    fontSize: 14,
    fontWeight: "500",
  },
  activeFilterText: {
    color: "white",
  },
  unreadCount: {
    backgroundColor: "#ff4757",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  unreadCountText: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
  },
  notificationsList: {
    flex: 1,
  },
  notificationContainer: {
    backgroundColor: "#2a2a2a",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
  },
  unreadNotification: {
    backgroundColor: "#252a3a",
  },
  notificationContent: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  notificationLeft: {
    position: "relative",
    marginRight: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  systemIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#3a3a3a",
    justifyContent: "center",
    alignItems: "center",
  },
  systemIcon: {
    fontSize: 24,
  },
  iconBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#1f87fc",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#2a2a2a",
  },
  iconBadgeText: {
    fontSize: 10,
  },
  notificationBody: {
    flex: 1,
  },
  notificationText: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 4,
  },
  userName: {
    color: "white",
    fontSize: 15,
    fontWeight: "600",
  },
  notificationMessage: {
    color: "#e0e0e0",
    fontSize: 15,
    lineHeight: 20,
  },
  amountContainer: {
    alignSelf: "flex-start",
    backgroundColor: "#1f87fc",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginVertical: 4,
  },
  amountText: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
  },
  timeText: {
    color: "#8e8e93",
    fontSize: 13,
    marginTop: 4,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1f87fc",
    marginLeft: 8,
    marginTop: 4,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    marginTop: 12,
    marginLeft: 60,
    gap: 12,
  },
  followBackButton: {
    backgroundColor: "#1f87fc",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    flex: 1,
    alignItems: "center",
  },
  followBackText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  viewProfileButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#1f87fc",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    flex: 1,
    alignItems: "center",
  },
  viewProfileText: {
    color: "#1f87fc",
    fontSize: 14,
    fontWeight: "600",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 80,
  },
  emptyStateIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyStateTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 8,
  },
  emptyStateText: {
    color: "#8e8e93",
    fontSize: 14,
    textAlign: "center",
  },
  quickActions: {
    flexDirection: "row",
    backgroundColor: "#2a2a2a",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#3a3a3a",
    gap: 12,
  },
  quickActionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3a3a3a",
    paddingVertical: 12,
    borderRadius: 8,
  },
  quickActionIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  quickActionText: {
    color: "white",
    fontSize: 14,
    fontWeight: "500",
  },
});

export default styles;
